package com.pavel.jogger.web.controller;

import com.pavel.jogger.service.AccessService;
import com.pavel.jogger.service.ReportService;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST Controller for generating and downloading document reports.
 * <p>
 * Unlike other controllers that return JSON data, this controller returns binary files (PDFs).
 * It is used for the "Export Data" functionality in the application.
 * </p>
 */
@RestController
@RequestMapping("/runners/{id}/reports")
public class ReportController {

    private final ReportService reportService;
    private final AccessService accessService;

    public ReportController(ReportService reportService, AccessService accessService) {
        this.reportService = reportService;
        this.accessService = accessService;
    }

    /**
     * Generates and downloads a PDF progress report for the specified runner.
     * <p>
     * This endpoint sets specific HTTP headers to trigger a file download in the browser/app.
     * The response body contains the raw bytes of the PDF file generated by the service.
     * </p>
     * @param id             The ID of the runner requesting the report.
     * @param authentication The security context to verify access rights.
     * @return A {@link ResponseEntity} containing the PDF bytes, with Content-Type set to 'application/pdf'
     * and Content-Disposition set to 'attachment' (triggering download).
     */
    @GetMapping("/progress")
    public ResponseEntity<byte[]> getProgressReport(
            @PathVariable Long id,
            Authentication authentication
    ) {
        accessService.checkRunnerAccess(authentication, id);

        byte[] pdf = reportService.generateProgressReport(id);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=progress_report_runner_" + id + ".pdf")
                .contentType(MediaType.APPLICATION_PDF)
                .body(pdf);
    }
}
